### ISSUE TITLE
Deprecate the ModelCardGenerator component

### ISSUE THREAD

**Issue by codesue** [tensorflow/model-card-toolkit#247]
We're moving the ModelCardGenerator component to tfx-addons. As part of this migration, we're removing the component and the tfx dependency from model-card-toolkit. Though we might move more TFX/MLMD related functionality from this project to tfx-addons in the future, the scope of this ticket is limited to removing the TFX component and dependency. 

## Tasks
- [ ] Remove the `ModelCardGenerator` component and associated files (in the `model_card_toolkit/tfx` directory) and add a deprecation warning with a note about the migration and workarounds / how to upgrade
- [ ] Remove the TFX/MLMD example notebook and the census income files from `model_card_toolkit/documentation/examples`
- [ ] Remove the `tfx` dependency
- [ ] Bump the upper limits of other dependencies to make model-card-toolkit compatible with newer versions of tfx
- [ ] Ensure that all tests related to this change pass
- [ ] Update relevant documentation to note that the component is being deprecated from model-card-toolkit and moved to tfx-addons. Link to the relevant issue/pull request in the tfx-addons repo.
